import yaml

with open("config.yaml", "r") as file:
    config = yaml.safe_load(file)

PITCH_RES = config["DISCRETIZATION"]["PITCH_RES"]
DYN_RES = config["DISCRETIZATION"]["DYN_RES"]
LENGTH_RES = config["DISCRETIZATION"]["LENGTH_RES"]
TIME_RES = config["DISCRETIZATION"]["TIME_RES"]
CHANNEL_RES = config["DISCRETIZATION"]["CHANNEL_RES"]
TEMPO_RES = config["DISCRETIZATION"]["TEMPO_RES"]

BAR_RES = config["RESOLUTION"]["BAR_RES"]

TEST_RATIO = config["MODEL_VALUES"]["TEST_RATIO"]
BATCH_SIZE = config["MODEL_VALUES"]["BATCH_SIZE"]
BLOCK_SIZE = config["MODEL_VALUES"]["BLOCK_SIZE"]
N_EMBD = config["MODEL_VALUES"]["N_EMBD"]
N_HEAD = config["MODEL_VALUES"]["N_HEAD"]
N_LAYER = config["MODEL_VALUES"]["N_LAYER"]
FEEDFORWARD_DIM = config["MODEL_VALUES"]["FEEDFORWARD_DIM"]
EPOCHS = config["MODEL_VALUES"]["EPOCHS"]
EVAL_INTERVAL = config["MODEL_VALUES"]["EVAL_INTERVAL"]
SAVE_INTERVAL = config["MODEL_VALUES"]["SAVE_INTERVAL"]
LEARNING_RATE = config["MODEL_VALUES"]["LEARNING_RATE"]
EVAL_ITERS = config["MODEL_VALUES"]["EVAL_ITERS"]
DROPOUT = config["MODEL_VALUES"]["DROPOUT"]
DEVICE = config["MODEL_VALUES"]["DEVICE"]
GENERATED_EVENT_LENGTH = config["MODEL_VALUES"]["GENERATED_EVENT_LENGTH"]
METADATA_DIMS = config["MODEL_VALUES"]["METADATA_DIMS"]
VOCAB_SIZE = sum(config["DISCRETIZATION"].values()) + 1

START_IDX = {}
START_IDX['PITCH_RES'] = 1
START_IDX['DYN_RES'] = START_IDX['PITCH_RES'] + PITCH_RES
START_IDX['LENGTH_RES'] = START_IDX['DYN_RES'] + DYN_RES
START_IDX['TIME_RES'] = START_IDX['LENGTH_RES'] + LENGTH_RES
START_IDX['CHANNEL_RES'] = START_IDX['TIME_RES'] + TIME_RES
START_IDX['TEMPO_RES'] = START_IDX['CHANNEL_RES'] + CHANNEL_RES

