DISCRETIZATION:
  PITCH_RES: 128
  DYN_RES: 128
  LENGTH_RES: 400
  TIME_RES: 400
  CHANNEL_RES: 128
  TEMPO_RES: 300

RESOLUTION:
  BAR_RES: 12

MODEL_VALUES:
  BATCH_SIZE: 16
  BLOCK_SIZE: 128
  MAX_ITERS: 60000
  EVAL_INTERVAL: 100
  SAVE_INTERVAL: 500
  LEARNING_RATE: 0.001
  EVAL_ITERS: 200
  N_EMBD: 256
  N_HEAD: 8
  N_LAYER: 8
  DROPOUT: 0.01
  DEVICE: "cuda"
  GENERATED_EVENT_LENGTH: 300
  METADATA_DIMS: {"composer": 8}
