discretization:
  pitch: 128
  dyn: 128
  length: 400
  time: 400
  channel: 128
  tempo: 300

resolution:
  bar_res: 12
  
values:
  block_len: 128
  device: 'cuda'
  metadata_dims: {"composer": 8}
  dropout: 0.01
  epochs: 200
  eval_interval: 100
  save_interval: 500
  learning_rate: 0.1
  eval_iters: 200
  test_ratio: 0.2
  batch_size: 8