discretization:
  pitch: 128
  dyn: 128
  length: 100
  time: 100
  channel: 256 # 128 instruments + 128 drum channels
  tempo: 250

resolution:
  bar_res: 24
  
values:
  block_len: 1024
  device: 'cuda'
  metadata_dims: {"composer": 8}
  dropout: 0.01
  epochs: 50
  eval_interval: 50
  save_interval: 1
  learning_rate: 0.005
  eval_iters: 200
  test_ratio: 0.2
  batch_size: 8