discretization:
  pitch: 128
  dyn: 128
  length: 100
  time: 100
  channel: 129 # 128 + drum channel
  tempo: 250

resolution:
  bar_res: 24
  
values:
  block_len: 512
  device: 'cuda'
  metadata_dims: {"composer": 8}
  dropout: 0.01
  epochs: 50
  eval_interval: 100
  save_interval: 50
  learning_rate: 0.005
  eval_iters: 200
  test_ratio: 0.2
  batch_size: 8