discretization:
  pitch: 128
  dyn: 128
  length: 500
  time: 500
  channel: 129 # 128 instruments + 1 drum channels
  tempo: 250

resolution:
  bar_res: 24

values:
  block_len: 1024 # 1024, 2048, 3000
  device: 'cuda'
  metadata_dims: {"composer": 8}
  dropout: 0.01
  epochs: 1000
  eval_interval: 10
  save_interval: 10
  learning_rate: 0.00005
  eval_iters: 200
  test_ratio: 0.5
  batch_size: 5
  augmentation: True
  end_of_seq: False
  start_of_seq: False

models:
  # No Finetuning
  classifier: "/scratch/s203861/pretrained/classifier/loss_0.01_time_2025-07-07-07-11-35.pth"
  # xlstm: "/scratch/s203861/pretrained/xlstm/loss_1.03_time_2025-07-18-04-33-10.pth"
  # mamba: "/scratch/s203861/pretrained/mamba/loss_1.07_time_2025-07-18-02-50-51.pth"
  # transformer: "/scratch/s203861/pretrained/transformer/loss_0.96_time_2025-07-18-09-43-23.pth"

  # Finedtuned
  xlstm: "/scratch/s203861/pretrained/xlstm/loss_1.05_time_2025-07-19-06-26-36.pth"
  mamba: "/scratch/s203861/pretrained/mamba/loss_1.11_time_2025-07-19-09-30-43.pth"
  transformer: "/scratch/s203861/pretrained/transformer/loss_0.96_time_2025-07-18-09-43-23.pth"

  # New Metadata
  # xlstm: "/scratch/s203861/pretrained/xlstm/loss_1.20_time_2025-07-23-07-49-09.pth"
  # mamba: "/scratch/s203861/pretrained/mamba/loss_1.29_time_2025-07-23-08-28-29.pth"
  # transformer: "/scratch/s203861/pretrained/transformer/loss_1.19_time_2025-07-23-07-36-09.pth"